### ISSUE TITLE
Add German language support

### ISSUE THREAD

**Issue by dtoakley** [fightforthefuture/digital-climate-strike#14]
As a German user I want to be able to see the digital strike content in German so that I can understand it. 

Acceptance Criteria:
- When I add German (or English) as a config option, I see the German text as it is defined in the code. 

Tech Notes:
- New LANGUAGE config option is added. 
- All hardcoded text in the HTML is updated with {content-name}
- German and English .yaml files added to /src dir
- Webpack build is updated to render iFrame using .yaml files and a rendering library like Mustache or handlebars. 
- utf-8 character types 
- Config value must match the name of the yaml file and is case sensitive. 

Out of scope:
- Any text formatting like upper or lowercasing. 
- Any content overriding of the translations

**Comment by dtoakley** [comment]
Check out how Fight for the Future did this: https://github.com/fightforthefuture/redalert-widget

**Comment by fviejobueno** [comment]
I am taking this issue

**Comment by dtoakley** [comment]
This was merged down in #31 . Closing this!
