### ISSUE TITLE
[TO DO] Work out what to show after September 20th...

### ISSUE THREAD

**Issue by dtoakley** [fightforthefuture/digital-climate-strike#25]

**Comment by jlevers** [comment]
Just some initial thoughts on this -- I would think most site owners probably wouldn't want content related to this showing up on their site after the day of the climate strike. Or maybe just a banner for a few days afterwards?

**Comment by dtoakley** [comment]
Yeah, our current solution is to not show the banner anymore -- which is what I think we want to go with. If any website wants to keep showing it, they can re-configure it via the options. Going to close this one off.
