### ISSUE TITLE
React component version

### ISSUE THREAD

**Issue by xdamman** [fightforthefuture/digital-climate-strike#55]
We can't drop in a javascript widget just like that because we are a single page web app. Which means that we should be able to change the state of the script depending on the page without a full reload (see https://github.com/opencollective/opencollective/issues/2360)

Would be great if someone could make a React component version of this widget.

**Comment by miloskroulik** [comment]
Shouldn't this have its own repo, though?

**Comment by dtoakley** [comment]
Yes, this would be its own repository. 

Right now, we don't have the capacity as a team to implement a React component. However I'm talking with some React devs early next week who might be able to take a stab at it, but I can't promise we'll get it down that soon. 

Here's some articles on dynamically loading scripts within React though: https://www.fullstackreact.com/articles/Declaratively_loading_JS_libraries/index.html & https://cleverbeagle.com/blog/articles/tutorial-how-to-load-third-party-scripts-dynamically-in-javascript -- maybe your team could do a tech spike (spend a few hours trying to see the implementation path), @xdamman ?
