### ISSUE TITLE
Date display in banner has undefined NaN

### ISSUE THREAD

**Issue by sgaghan** [fightforthefuture/digital-climate-strike#56]
Mac 10.14.6, Chrome 76.0.3809.100
<img width="1979" alt="Screen Shot 2019-08-29 at 9 37 47 AM" src="https://user-images.githubusercontent.com/54674064/63945339-255c4600-ca41-11e9-8a32-bcb77c6c3516.png">

**Comment by sturosier** [comment]
I'm taking a look at this one.

**Comment by sturosier** [comment]
Confirmed that this is working fine now.
