### ISSUE TITLE
Add Czech language support

### ISSUE THREAD

**Issue by miloskroulik** [fightforthefuture/digital-climate-strike#57]
As a Czech user I want to be able to see the digital strike content in Czech so that I can understand it.

Depends on merge of #31

**Comment by miloskroulik** [comment]
PR added: #63

**Comment by miloskroulik** [comment]
PR merged, but no `index-cs.html` file built so far.

**Comment by miloskroulik** [comment]
Should be fixed once #65 is merged.

**Comment by dtoakley** [comment]
We're live: http://assets.digitalclimatestrike.net/demo.html?language=cs

**Comment by dtoakley** [comment]
If that looks good to you @miloskroulik - please close this issue down :)

**Comment by miloskroulik** [comment]
Looks good, closing.
