### ISSUE TITLE
Demo page should be directly available in all supported localizations

### ISSUE THREAD

**Issue by miloskroulik** [fightforthefuture/digital-climate-strike#62]
Unless I'm missing something, the demo page is available in the English only. It would be useful to have a simple way to have this page available in every supported language. I know that the demo page should adjust to the language set in the users browser, but some users use a different locale so they might be confused by a "missing" localization.

**Comment by dtoakley** [comment]
It does -- just provide it the language parameter. E.g. http://assets.digitalclimatestrike.net/demo.html?language=de

I've updated the README with a sentence that makes this clear. Closing this one.
