### ISSUE TITLE
Banner in German and English?

### ISSUE THREAD

**Issue by rwagels** [fightforthefuture/digital-climate-strike#86]
Hey
I run a website based on Joomla in German and English using the core functions of Joomla for multi language sites. I added the banner using the script and a module.  Problem: The banner is always in German, no matter what language the site is in. Is there a way to provide the German version only to the german visitors?
Thanks
Rolf

**Comment by rwagels** [comment]
Never mind. Just realised it displays the banner based on navigator.language setting in the browser. That should do the trick!

**Comment by deLinhuberin** [comment]
The script uses the preferred browser language, try to change the lang in your browser settings and test again.
Or use the customization options - -> code, scroll down a bit

Gerne!
Marion

**Comment by rwagels** [comment]
Yep, just realized this myself...sorry!
Our answers crossed in time :-)
Grüße
Der Rolf
