### ISSUE TITLE
Cannot get widget to work

### ISSUE THREAD

**Issue by debrudnick** [fightforthefuture/digital-climate-strike#87]
I tried to embed your code on our home page, www.sustainablebainbridge.org. It just shows up as a line of code, not as the widget.

**Comment by dtoakley** [comment]
Hi @debrudnick -- I see it working fine on the link you provided :) However I also see that you have added it in 3 different places? 

If you can provide additional information about how you added it, and the browser/operating sytem that you are trying to view it on, we might be able to help more.

**Comment by debrudnick** [comment]
Ah- I see that now. I think I fixed it. Thenks!
